Lesson11
Sinlerwim/nix_12 pull request #3
Opened 2022-07-15 12:03 UTC by Sinlerwim

У Creating, Deleteting, Updating все методы, кроме start() приватные. Их не тестировал

2022-07-15 23:10 UTC, Fabolo12 requested changes
Не увидел
ArgumentCaptor
Calling real methods
THROWING EXCEPTIONS

2022-07-15 23:10 UTC, Fabolo12 commented on src/main/java/com/service/AutoService.java
> +    private final AutoRepository AUTO_REPOSITORY;
Теперь это не константа, а значит другой стиль

2022-07-15 23:10 UTC, Fabolo12 commented on src/main/java/com/Main.java
> +                Creating.start(reader, AUTO_SERVICE, BUS_SERVICE, TRUCK_SERVICE);
Лучше создавать обьекты, а то приходится все писать в статике, а это нарушение ООП

2022-07-15 23:10 UTC, Fabolo12 commented on src/test/java/com/repository/AutoRepositoryTest.java
> +        auto = Mockito.mock(Auto.class);
А зачем тебе мок модели, это лишнее

2022-07-15 23:10 UTC, Fabolo12 commented on src/test/java/com/repository/AutoRepositoryTest.java
> +        target = Mockito.mock(AutoRepository.class);
Проверяемый класс мы не мокируем

2022-07-15 23:10 UTC, Fabolo12 commented on src/test/java/com/repository/AutoRepositoryTest.java
> +        }));
Ну и соответственно эта проверка имеет смысл где-то в сервисе

2022-07-15 23:10 UTC, Fabolo12 commented on src/test/java/com/service/AutoServiceTest.java
> +    }
Тут нет проверок

2022-07-16 06:30 UTC, Sinlerwim commented on src/main/java/com/Main.java
> +                Creating.start(reader, AUTO_SERVICE, BUS_SERVICE, TRUCK_SERVICE);
Я когда-то пытался так. Втдтмо для этого нужно многопоточность освоить. Потому что, если правильно помню, то при выходе из метода, потом закрывается и кладет за собой все остальные

2022-07-16 06:37 UTC, Sinlerwim commented
> Не увидел ArgumentCaptor Calling real methods THROWING EXCEPTIONS

THROWING EXCEPTIONS насколько помню, был в тесте какого-то из getById

2022-07-20 23:37 UTC, Fabolo12 approved these changes

2022-07-24 14:39 UTC, merged