Lesson17
Sinlerwim/nix_12 pull request #9
Opened 2022-08-06 15:36 UTC by Sinlerwim

2022-08-06 15:42 UTC, Sinlerwim commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/akeCrtlj/82-io-nio)

2022-08-06 22:12 UTC, Fabolo12 requested changes

2022-08-06 22:12 UTC, Fabolo12 commented on src/main/java/com/Main.java
> +                System.out.println("Choose the action you need (1-7) or 0 to exit:");
А тут ошибка, потому что хардкор

2022-08-06 22:12 UTC, Fabolo12 commented on src/main/java/com/Main.java
> +        final File xml = new File("src/main/resources/Auto.xml");
Неправильное чтение

2022-08-06 22:12 UTC, Fabolo12 commented on src/main/java/com/Main.java
>  public class Main {
Вообще этот класс давно уже пора дробить на отдельные классы и методы...

2022-08-07 21:26 UTC, Fabolo12 approved these changes

2022-08-12 13:17 UTC, merged